[build]
  command = "npm run build"
  publish = "public" # O Remix usará o diretório `public` para servir os assets estáticos
  functions = "netlify/functions" # Onde as Netlify Functions são armazenadas

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
